name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Ruby (needed for Jekyll)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Match your local Ruby version
          bundler-cache: true
      
      - name: Remove Gemfile.lock (to avoid platform mismatch)
        run: rm -f Gemfile.lock

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3


      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Build Jekyll site
      - name: Build site with Jekyll
        run: bundle exec jekyll build

      # Deploy via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site
