name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: false   # Disable cache for now, to rebuild cleanly

      # Re-generate Gemfile.lock for Linux
      - name: Recreate Gemfile.lock for Linux
        run: |
          rm -f Gemfile.lock
          bundle lock --add-platform x86_64-linux
          bundle install --jobs 4 --retry 3

      # Build Jekyll site
      - name: Build site with Jekyll
        run: bundle exec jekyll build

      # Deploy via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: /httpdocs/            # root of your domain
          protocol: ftp
          port: 21
          passive: true
          dangerous-clean-slate: true   # wipes server dir before deploying
